version: '3.8'
services:
  api:
    build: ./backend
    volumes: 
      - logs:/app/logs
      - /app/node_modules

  client:
    build: ./frontend
    stdin_open: true
    tty: true


    depends_on: 

      - api

  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - api
      - client
  
volumes: 

  logs:
