{
 "title": "Kubernetes overview",
 "description": "all the k8s resources",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Node Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  100 * (1 - avg(node_memory_MemAvailable_bytes) by (instance) / avg(node_memory_MemTotal_bytes) by (instance))\n  * on(instance) group_left(nodename) node_uname_info,\n  \"instance\", \"\", \"instance\", \".*\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100))\n  * on(instance) group_left(nodename) node_uname_info,\n  \"instance\", \"\", \"instance\", \".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  100 * (\n    sum by (instance) (node_filesystem_size_bytes{device!=\"rootfs\"})\n    - sum by (instance) (node_filesystem_free_bytes{device!=\"rootfs\"})\n  ) / sum by (instance) (node_filesystem_size_bytes{device!=\"rootfs\"})\n  * on(instance) group_left(nodename) node_uname_info,\n  \"instance\", \"\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Namespaces count",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{phase=\"Active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "description": "total number of pods",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)\n", "legendFormat": "__auto" }
   ]
  }
 ]
}