apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-001
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 5
    ssh:
      allow: false
    