apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: test1 # change to your release name, must match the release name of your Prometheus operator
  name: kube-pod-not-ready
  namespace: goals-ns   #important: must match the namespace where you want alerting
spec:
  groups:
  - name: goals-pods-alerts
    rules:
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
      for: 1m # adjust the duration as needed
      labels:
        project: goals
        severity: critical
      annotations:
        summary: Kubernetes Pod {{ $labels.pod }} not healthy 
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for longer than 1 minute.\n"     

    # kubectl create deployment crashloop-ubuntu --image=ubuntu -- /bin/sh -c "echo 'Crashing now...' && exit 1"
    - alert: KubernetesPodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
      for: 1m  #adjust the duration as needed
      labels:
        project: goals  
        severity: critical
      annotations:
        summary: Kubernetes pod {{ $labels.pod }} crash looping
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping\n"


    - alert: ContainerHighCpuUtilization
      expr: (sum by (pod) (rate(container_cpu_usage_seconds_total{container!=""}[1m]))/sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits) by (pod)) * 100 > 80
      for: 1m
      labels:
        project: goals
        severity: warning
      annotations:
        summary: Container High CPU utilization
        description: "Container {{ $labels.namespace }}/{{ $labels.pod }} CPU utilization is above 80%\n"

    - alert: ContainerHighMemoryUsage
      expr: (sum by (namespace, pod) (container_memory_working_set_bytes{container!=""}) / sum by (namespace, pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{container!=""})) * 100 > 80
      for: 1m
      labels:
        project: goals
        severity: warning
      annotations:
        summary: Container High Memory usage
        description: "Container {{ $labels.namespace }}/{{ $labels.pod }} Memory usage is above 80%\n"
# dont know
    - alert: KubernetesContainerOomKiller
      expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
      for: 0m
      labels:
        project: goals
        severity: critical
      annotations:
        summary: Kubernetes Container oom killer
        description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.\n"
